### ISSUE TITLE
[BUG] Ray core_worker_process fails when running on a full node on ThetaGPU

### ISSUE THREAD

**Issue by megh1241** [deephyper/deephyper#134]
**Describe the bug**
When I try to run the following example in the tutorial (https://deephyper.readthedocs.io/en/latest/tutorials/tutorials/alcf/02_ThetaGPU/README.html) on ThetaGPU, I get the following error.

core_worker.cc:194:  Check failed: core_worker_process The core worker process is not initialized yet or already shutdown.^M
^[[2m^[[36m(pid=3103399)^[[0m *** StackTrace Information ***^M
^[[2m^[[36m(pid=3103399)^[[0m     ray::SpdLogMessage::Flush()^M
^[[2m^[[36m(pid=3103399)^[[0m     ray::RayLog::~RayLog()^M
^[[2m^[[36m(pid=3103399)^[[0m     ray::core::CoreWorkerProcess::EnsureInitialized()^M
^[[2m^[[36m(pid=3103399)^[[0m     ray::core::CoreWorkerProcess::GetCoreWorker()^M
^[[2m^[[36m(pid=3103399)^[[0m     __pyx_pw_3ray_7_raylet_10CoreWorker_23get_worker_id()^M
^[[2m^[[36m(pid=3103399)^[[0m     method_vectorcall_NOARGS^M
^[[2m^[[36m(pid=3103399)^[[0m ^M

**To Reproduce**
Run the scripts suggested in https://deephyper.readthedocs.io/en/latest/tutorials/tutorials/alcf/02_ThetaGPU/README.html as it is except for the conda version. I used module load conda/2021-11-30 (instead of conda/2021-09-22 as suggested in the tutorial.

**Expected behavior**

**Screenshots**
<img width="1487" alt="Screen Shot 2022-05-19 at 9 53 08 AM" src="https://user-images.githubusercontent.com/11406990/169326428-a2fc7ac0-e363-4d56-81c6-baf6b1e73e94.png">

**Desktop (please complete the following information):**
 -ThetaGPU 
-pre-installed version of deephyper in conda/2021-09-22

**Additional context**
The rest of it runs correctly I think because results.csv gets generated and the NAS search takes place.

**Comment by Deathn0t** [comment]
Hello @megh1241 , sorry for the delay,
So did you manage to run your experiment with this error?
Did you check if the number of workers was correctly detected by the evaluator? `evaluator.num_workers`
What is the context of your execution (number of nodes, number of GPUs per task)

**Comment by Deathn0t** [comment]
Hello @megh1241 we just release a new version of the software `pip install deephyper==0.4.0` that includes MPI evaluators which should not have this type of issue checkout [this tutorial](https://deephyper.readthedocs.io/en/latest/tutorials/tutorials/alcf/03_ThetaGPU_mpi/README.html) and let me know if it helps

**Comment by megh1241** [comment]
Hi, sorry for the late reply. I think the number of workers I initialized in my qsub script and in the evaluator was not consistent - hence the error. I managed to resolve it. Thank you.
