### ISSUE TITLE
Adding operations (attention layers) which have multiple inputs in call for NAS

### ISSUE THREAD

**Issue by OliVandy** [deephyper/deephyper#145]
I am working in the Argonne conda/2021-11-30 environment. This problem is about the search space so I've been testing it on a single gpu.

The problem is how to include an operation based on the MultiHeadAttention layers in keras. When called these layers take in tensors for query, value, and optionally key. My current problem is figuring out how to provide these in the search space. By using the NxSearchSpace connect method I can link up the nodes to provide the query tensor, but I haven't been able to figure out how to put in the value tensor and am getting an error when I try to sample from the search space that the value is missing during the call. 

The goal is to include these layers in the search space so that they will potentially appear in the sampled models. A test script which includes the search space and samples and plots a single model from it is attached. Currently all attention layers in the script are commented out and a concatenate is used to put the encoder outputs and decoder inputs, this will instead be done with an attention layer with query the decoder input and value the encoder output.

[transformer_NAS_test.txt](https://github.com/deephyper/deephyper/files/8978506/transformer_NAS_test.txt)

**Comment by Deathn0t** [comment]
Hello @OliVandy ,

To be compatible with the NAS API you have to first define a custom layer to have only 1 input to the `call` function of Keras:
```python
#* create a wrapping layer to have only on input list to call(self, inputs)
@operation
class MHAttention(tf.keras.layers.MultiHeadAttention):
    def call(self, inputs):
        return super().call(query=inputs[0], value=inputs[1])
```

Then you have to create intermediate nodes to represent the `query` and `value` such as:
```python
        #* create intermediate nodes to represente query and values
        query = ConstantNode(Identity())
        self.connect(x, query)
        value = ConstantNode(Identity())
        self.connect(x, value)
```

Then you can do the following with the Attention layer:
```python
        # This will be a potential self attention layer on the decoder inputs
        attention = VariableNode()
        attention.add_op(MHAttention(num_heads=n_heads, key_dim=self.embed_dim))
        self.connect(query, attention)
        self.connect(value, attention)
        x = attention
```

Here is the full script:
[transformer_NAS_test.txt](https://github.com/deephyper/deephyper/files/8989607/transformer_NAS_test.txt)

Also be careful with the input/output shapes of the data. I modified them to have something running.

Here is an output showing that it works:
![model](https://user-images.githubusercontent.com/5201978/175885388-a4c8dd0a-d518-4f3d-b3b0-51575d6bf7bf.png)
