### ISSUE TITLE
[Warning] trigger tf.function retracing

### ISSUE THREAD

**Issue by megh1241** [deephyper/deephyper#149]
**Describe the bug**
I get the following warning in a NAS workflow: 
WARNING:tensorflow:5 out of the last 13 calls to <function Model.make_test_function.<locals>.test_function at 0x7f20f752edc0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details. 

**To Reproduce**
I'm trying to perform a NAS on the candle learning benchmark. I use a RegularizedEvolution search and a ray evaluator backend. I'm using the problem, search space and load_data fn defined here https://github.com/deephyper/candlepb/tree/master/candlepb/NT3/problems . 

```
evaluator = Evaluator.create(
    run_base_trainer,
    method="ray",
    method_kwargs={
        "address": 'auto',
        "num_cpus_per_task": args.num_cpus_per_task,
        "num_gpus_per_task": args.num_gpus_per_task,
        "callbacks": [LoggerCallback()],
    },
)

search = RegularizedEvolution(problem, evaluator, random_state=args.rand_seed, log_dir=args.save_result_dir, sample_size=args.sample_size, population_size=args.population_size)
results = search.search(args.search_attempts)
```

**Desktop (please complete the following information):**
 - System: [Theta, ThetaGPU, Cooley, local]
 - Python version [3.8]
 - DeepHyper Version [0.3.3]
 -I',m training on just 1 GPU. The error persists even when training on a CPU.
-installed tensorflow-gpu using "conda install tensorflow-gpu" . I think this defaults to TF 2.4

**Misc details
This seems to be a known issue in older versions of tensorflow (https://github.com/tensorflow/tensorflow/issues/34025) . However, none of the suggestions seemed directly applicable. 

I was wondering if this behavior is expected or if it implies there's a bug on my side. 

Thanks!

**Comment by Deathn0t** [comment]
Hello @megh1241 , 
I am not sure about this. In order to identify if this is coming from the installation or system could you try this tutorial:
* https://deephyper.readthedocs.io/en/latest/tutorials/tutorials/colab/NAS_basic.html
and let me know if the same problem happens.
Also, could you share with me the search space file and problem file, I can help you update them so that it is compatible with the latest version of deephyper. In particular the search space definition could play a role here.
