### ISSUE TITLE
[BUG] Key error halfway through configuration search

### ISSUE THREAD

**Issue by nviz2** [deephyper/deephyper#153]
Hello!  I am trying to implement hyperparameter optimization on a fairly simple NN regression model, and I have the max_evals set to 20.  Once the search is 50% complete, I get KeyError: 'squared_error'.

Here is the cell that causes the error:
<img width="687" alt="Screenshot 2022-07-20 144219" src="https://user-images.githubusercontent.com/106704775/180068013-b30bfed9-e97e-473a-af1b-b134eb63fca2.png">

And here is the full error log:

> KeyError                                  Traceback (most recent call last)
> <ipython-input-23-8749cfa7b586> in <module>
>       4 
>       5 search = CBO(problem, run, initial_points=[problem.default_configuration], log_dir="cbo-results", random_state=42)
> ----> 6 results = search.search(max_evals=20)
> 
> ~/.local/lib/python3.8/site-packages/deephyper/search/_search.py in search(self, max_evals, timeout)
>     129 
>     130         try:
> --> 131             self._search(max_evals, timeout)
>     132         except SearchTerminationError:
>     133             if "saved_keys" in dir(self):
> 
> ~/.local/lib/python3.8/site-packages/deephyper/search/hps/_cbo.py in _search(self, max_evals, timeout)
>     264 
>     265                 if len(opt_y) > 0:
> --> 266                     self._opt.tell(opt_X, opt_y)
>     267                     logging.info(f"Fitting took {time.time() - t1:.4f} sec.")
>     268 
> 
> ~/.local/lib/python3.8/site-packages/deephyper/skopt/optimizer/optimizer.py in tell(self, x, y, fit)
>     784                 y = list(y)
>     785                 y[1] = log(y[1])
> --> 786         return self._tell(x, y, fit=fit)
>     787 
>     788     def _tell(self, x, y, fit=True):
> 
> ~/.local/lib/python3.8/site-packages/deephyper/skopt/optimizer/optimizer.py in _tell(self, x, y, fit)
>     834                 warnings.simplefilter("ignore")
>     835                 Xtt = self.space.imp_const.fit_transform(self.space.transform(Xi))
> --> 836                 est.fit(Xtt, yi)
>     837 
>     838             # for qLCB save the fitted estimator and skip the selection
> 
> /opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_forest.py in fit(self, X, y, sample_weight)
>     385             # parallel_backend contexts set at a higher level,
>     386             # since correctness does not rely on using threads.
> --> 387             trees = Parallel(n_jobs=self.n_jobs, verbose=self.verbose,
>     388                              **_joblib_parallel_args(prefer='threads'))(
>     389                 delayed(_parallel_build_trees)(
> 
> /opt/anaconda3/lib/python3.8/site-packages/joblib/parallel.py in __call__(self, iterable)
>    1039             # remaining jobs.
>    1040             self._iterating = False
> -> 1041             if self.dispatch_one_batch(iterator):
>    1042                 self._iterating = self._original_iterator is not None
>    1043 
> 
> /opt/anaconda3/lib/python3.8/site-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
>     857                 return False
>     858             else:
> --> 859                 self._dispatch(tasks)
>     860                 return True
>     861 
> 
> /opt/anaconda3/lib/python3.8/site-packages/joblib/parallel.py in _dispatch(self, batch)
>     775         with self._lock:
>     776             job_idx = len(self._jobs)
> --> 777             job = self._backend.apply_async(batch, callback=cb)
>     778             # A job can complete so quickly than its callback is
>     779             # called before we get here, causing self._jobs to
> 
> /opt/anaconda3/lib/python3.8/site-packages/joblib/_parallel_backends.py in apply_async(self, func, callback)
>     206     def apply_async(self, func, callback=None):
>     207         """Schedule a func to be run"""
> --> 208         result = ImmediateResult(func)
>     209         if callback:
>     210             callback(result)
> 
> /opt/anaconda3/lib/python3.8/site-packages/joblib/_parallel_backends.py in __init__(self, batch)
>     570         # Don't delay the application, to avoid keeping the input
>     571         # arguments in memory
> --> 572         self.results = batch()
>     573 
>     574     def get(self):
> 
> /opt/anaconda3/lib/python3.8/site-packages/joblib/parallel.py in __call__(self)
>     260         # change the default number of processes to -1
>     261         with parallel_backend(self._backend, n_jobs=self._n_jobs):
> --> 262             return [func(*args, **kwargs)
>     263                     for func, args, kwargs in self.items]
>     264 
> 
> /opt/anaconda3/lib/python3.8/site-packages/joblib/parallel.py in <listcomp>(.0)
>     260         # change the default number of processes to -1
>     261         with parallel_backend(self._backend, n_jobs=self._n_jobs):
> --> 262             return [func(*args, **kwargs)
>     263                     for func, args, kwargs in self.items]
>     264 
> 
> /opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/fixes.py in __call__(self, *args, **kwargs)
>     220     def __call__(self, *args, **kwargs):
>     221         with config_context(**self.config):
> --> 222             return self.function(*args, **kwargs)
> 
> /opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_forest.py in _parallel_build_trees(tree, forest, X, y, sample_weight, tree_idx, n_trees, verbose, class_weight, n_samples_bootstrap)
>     167                                                         indices=indices)
>     168 
> --> 169         tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
>     170     else:
>     171         tree.fit(X, y, sample_weight=sample_weight, check_input=False)
> 
> /opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py in fit(self, X, y, sample_weight, check_input, X_idx_sorted)
>    1245         """
>    1246 
> -> 1247         super().fit(
>    1248             X, y,
>    1249             sample_weight=sample_weight,
> 
> /opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py in fit(self, X, y, sample_weight, check_input, X_idx_sorted)
>     348                                                          self.n_classes_)
>     349             else:
> --> 350                 criterion = CRITERIA_REG[self.criterion](self.n_outputs_,
>     351                                                          n_samples)
>     352 
> 
> KeyError: 'squared_error'
> 

 - OS: Linux
 - Python version 3.8.8
 - DeepHyper Version 0.4.0

Any help would be appreciated!

**Comment by Deathn0t** [comment]
This error is coming from an outdated version of scikit-learn. Can you update both deephyper and scikit-learn?

```
pip install --upgrade deephyper scikit-learn
```

**Comment by nviz2** [comment]
Yes, thank you!  That was the fix, I probably should've checked the versions first.  Sorry to trouble you for something so small.

**Comment by Deathn0t** [comment]
Great! Happy to know it resolved the problem. Do not hesitate to contact us again in case of problem.
