### ISSUE TITLE
[FAQ] Regarding reusing tf dataset object in trials

### ISSUE THREAD

**Issue by sibyjackgrove** [deephyper/deephyper#154]
**Context**
Platform: Single computing node with 2 GPU's.
OS: Linux

**Describe the task you are trying to achieve.**
I am trying to optimize hyperparameters for a Denoising AutoEncoder.  I have an existing method that returns TF datasets that I can pass into the fit method. Currently, I am using it as follows with DeepHyper.

```
def build_and_train_autoencoder(....):
    .....
    ....
    train_ds = get_dataset_from_csv(train_csv_files,....)
    test_ds = get_dataset_from_csv(test_csv_files,....) 

   autoencoder = Denoise1DCNNDeepHyper()
   history = autoencoder.fit(train_ds ,test_ds ....)

   return autoencoder, history.history


def run(config):
    # important to avoid memory exploision
    tf.keras.backend.clear_session()
    
    _, history = build_and_train_autoencoder(config, verbose=1)

    return -history["val_loss"][-1]

.......
.......

search = CBO(problem, run, .....)
results = search.search(max_evals=10)
    
```

However, in the above code, the `get_dataset_from_csv` is getting called every time a new trial is started. A more elegant way would be for `train_ds` and `test_ds` to be created just once and then used for all the trials.

**Describe the solution you'd like**
A preferable solution would be to be able to pass additional arguments when creating the `search `object that can be used by the `run `method.

**Comment by Deathn0t** [comment]
Hello @sibyjackgrove ,

What you are describing is either possible through `run_function_kwargs` when defining an `Evaluator` or by using `functools.partial` such as
```python
import functools

def run(config, data):
  ...

run_bind = functools.partial(run_bian, data=data)

search = CBO(problem, run_bind)
...
```

However, you must be careful with this scheme especially if you leverage parallelisation where data will be serialised and sent to remote workers (which can be significantly slow). A possibility in this case is to cache data locally on each compute node.

**Comment by Deathn0t** [comment]
Hello @sibyjackgrove did the previous comment answered your question?

**Comment by sibyjackgrove** [comment]
@Deathn0t Apologies for not getting back earlier. Yes, this is the solution I was looking for.
