### ISSUE TITLE
[FEATURE] Expose `initial_point_generator` and `base_estimator` settings from skopt.Optimizer in HPS

### ISSUE THREAD

**Issue by albertkklam** [deephyper/deephyper#156]
**Is your feature request related to a problem? Please describe.**
The current `CBO` class only allows a subset of the parameters in the `skopt.Optimizer` class as inputs. For instance, `initial_point_generator` cannot be passed to `CBO` although it is a parameter in `skopt.Optimizer` and is in essence hard-coded to the default value when setting the optimizer in `CBO`. Similarly, the `surrogate_model` parameter in `CBO` sets predefined regressors based on an input string, although `skopt.Optimizer` allows any `sklearn` regressor as a `base_estimator`.

**Describe the solution you'd like**

- A`initial_point_generator` parameter in the `CBO` class itself that gets passed to the optimizer. 
- Expansion of `surrogate_model` to allow the user to pass their own `sklearn` regressor to the underlying `base_estimator` parameter of the optimizer.

**Additional context**
I can make a pull request with these changes since I've implemented these on my own fork, but it would be good to get another pair of eyes across the changes. I've only used `CBO` in my work so far, but after a quick scan of `DBO`, it looks like these are also unavailable in that class so it may be a good idea to make the same changes there.

**Comment by Deathn0t** [comment]
Hello @albertkklam,

I think this is a good idea. To avoid creating new arguments, maybe`initial_points` for `initial_point_generator` could be used, and if a `str` or `object` is passed it can be detected and we can make the difference with having `None` or a `list` of points.

For the `surrogate_model` make sure to document how the `n_jobs` parameter will behave if the surrogate model instance is directly passed. Also, I think we need to be careful with how the data-preprocessing is handled depending on the surrogate model (for example normalisation of collected `(x, y)` values).

You can create a PR, and I can help review/test it.

**Comment by albertkklam** [comment]
Addressed in https://github.com/deephyper/deephyper/pull/157 and https://github.com/deephyper/deephyper/pull/158.
