### ISSUE TITLE
[Doc] DeepHyper documentation on NERSC webpage

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/deephyper#160]
Add documentation about how to use DeepHyper on Perlmutter.

- [x] write draft documentation in markdown (send to @Deathn0t for review)
- [ ] add `site/NERSC/Perlmutter` to https://github.com/deephyper/quickstart (creates PR and follow Polaris, ThetaGPU examples)
- [x] add installation documentation **Perlmutter (NERSC)** to https://deephyper.readthedocs.io/en/latest/install/index.html (creates PR)
- [x] add documentation to the https://docs.nersc.gov/machinelearning/hpo/ (contact support)

**Comment by Deathn0t** [comment]
@nesar started to create the following documentation https://github.com/nesar/DeepHyperSwing/blob/main/saul/perlmutter.rst

**Comment by nesar** [comment]
@Deathn0t I have the correction here in the develop branch: https://github.com/deephyper/deephyper/edit/develop/docs/install/nersc.rst

**Comment by Deathn0t** [comment]
@nesar great thanks. I noticed that for me removing `$ conda install gxx_linux-64 gcc_linux-64` still makes the installation works. Also it would be great, to show what is installing:
* the basic deephyper
* the mpi4py package for MPICommEvaluator
* the tensorflow dependencies for NAS
Because often not all of these dependencies are required
