### ISSUE TITLE
Update license badge

### ISSUE THREAD

**Issue by wildsm** [deephyper/deephyper#164]
Related to #163 

Once pypi is updated, need to confirm that [README.md](https://github.com/deephyper/deephyper/blob/master/README.md)  has new badge reflecting BSD 3-Clause:

`![PyPI - License](https://img.shields.io/pypi/l/deephyper.svg)`

**Comment by Deathn0t** [comment]
I can update this in the `setup.cfg` file. @wildsm do you know if the `version` which appears in the `LICENSE.md` should match the version of the software or not?

**Comment by wildsm** [comment]
I would pull the version from the LICENSE to avoid things becoming out of sync. Examples:

https://github.com/petsc/petsc/blob/main/LICENSE
https://github.com/parmoo/parmoo/blob/develop/LICENSE

**Comment by Deathn0t** [comment]
yes, so in both example, no version is put in the `LICENSE`

**Comment by wildsm** [comment]
My preferred first 2 lines would be:
`Copyright (c) 2018-2022, UChicago Argonne, LLC and the DeepHyper Development Team
All Rights Reserved.`

Optionally could add an intermediary line that lists the (initial?) team (Prasanna Balaprakash, Romain Egele, Misha Salim, Venkat Vishwanath, and Stefan Wild).

**Comment by Deathn0t** [comment]
I propose to refactor the header of the `LICENSE` from

```
Copyright 2018, Argonne National Laboratory
All Rights Reserved
DeepHyper, Version 0.1
Prasanna Balaprakash, Romain Egele, Misha Salim, Venkat Vishwanath, and Stefan Wild.
```

to 


```
Copyright (c) 2018-2022, UChicago Argonne, LLC and the DeepHyper Development Team
All Rights Reserved
```

If this is okay, I think we are done.

**Comment by wildsm** [comment]
I think we're on the same page, let me know if you want a PR or review of one
