### ISSUE TITLE
[Doc] Best practices documentation for scaling

### ISSUE THREAD

**Issue by venkat-1** [deephyper/deephyper#18]
It will be very valuable to have a best practices documentation on how one should scale a problem on large-scale systems with DeepHyper. What scale sizes should one evaluate, such as 8, 16, 32 nodes first? Next, when should one be ready to scale out and the parameters involved here.

**Comment by Deathn0t** [comment]
Hi @venkat-1 , 
I started to add this page in the documentation: [Choosing & Scaling a Search](https://deephyper.readthedocs.io/en/latest/user_guides/choosing_scaling.html). It contains advice on how to safely use the software, how to choose, and scale a given search.

**Comment by venkat-1** [comment]
Thanks for starting this. It is a good start and it would be value to provide more information in the near future

Some thoughts:
-  When does one scale to 32 and next to 64/128 before targeting 256.
-  Are there any specific recommendation in HPS for scaling? Any additional information about the search methods, their applicability/use-cases, and scalability?
- Are they any  specific recommendation in NAS for scaling
- What are suggestions for data staging?



On Apr 26, 2020, at 5:05 AM, Romain Egele <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @venkat-1<https://github.com/venkat-1> ,
I started to add this page in the documentation: Choosing & Scaling a Search<https://deephyper.readthedocs.io/en/latest/user_guides/choosing_scaling.html>. It contains advice on how to safely use the software, how to choose, and scale a given search.

**Comment by Deathn0t** [comment]
Hello @venkat-1 , 

After my recent work on Bayesian Optimization, I added more information about scaling on the new F.A.Q. page, mainly about how to set the parameters of the BO algorithm when scaling:  
* https://deephyper.readthedocs.io/en/latest/faq.html#how-to-scale-bo 

We also provided features and tutorials to profile more precisely the worker utilisation and detect possible overheads:
* https://deephyper.readthedocs.io/en/latest/tutorials/tutorials/scripts/03_Evaluators/README.html

We are still missing information about **data staging**, we should say something about staging in local memory or SSD as well as leveraging broadcasting when MPI is used (for these I/O specificities I am not sure to be the best expert but I can write simples things about how we do it in practice).
