### ISSUE TITLE
TypeError in GaussianProcessRegressor.fit() during CBO search

### ISSUE THREAD

**Issue by theSubsurfaceGuy** [deephyper/deephyper#192]
**Describe the bug**
(CBO) search method unexpectedly fails during a run with an error related to an unexpected argument 'sample_weight' in GaussianProcessRegressor.fit(), works completely fine with default surrogate model. 

**To Reproduce**
1. Define an HpProblem instance.
2. Define the search instance using the CBO method.
3. Set the max_evals parameter in the search method to 50
4. During the run, after a certain number of evaluations (10), the program throws a TypeError: GaussianProcessRegressor.fit() got an unexpected keyword argument 'sample_weight'. 

**Expected behavior**
The CBO search should successfully perform the specified number of evaluations without encountering an unexpected argument error in the underlying optimization process.

**Screenshots** 
<img width="1114" alt="Screenshot 2023-06-12 at 5 44 16 PM" src="https://github.com/deephyper/deephyper/assets/70286881/cad6ccbc-1143-47fe-9a2b-5019acb0d3a5">

**Desktop (please complete the following information):**
 Running on google collab the same issue when running on HPC cluster 
Python version: Python 3.10.12 same issue with 3..9.16
DeepHyper Version: 0.5.0

**Comment by Deathn0t** [comment]
Hello @theSubsurfaceGuy , the description and screenshot is great. Could you please copy/paste the code from the screenshot so that I do not need to rewrite it? Thank you.

**Comment by theSubsurfaceGuy** [comment]
Hello @Deathn0t, here is the code

from deephyper.problem import HpProblem
from deephyper.evaluator import Evaluator
from deephyper.search.hps import CBO

def objective(hyperparameters):
    x = hyperparameters["x"]
    return (x-5)**2

problem = HpProblem()
problem.add_hyperparameter((1, 10), "x")

evaluator = Evaluator.create(objective, method="process")

search = CBO(problem=problem, evaluator=evaluator, surrogate_model='GP', random_state=42)

results = search.search(max_evals=50)

**Comment by Deathn0t** [comment]
@theSubsurfaceGuy I fixed it here: https://github.com/deephyper/deephyper/commit/3a41ac156751df106c1880b029718f1fea33e783

You can checkout the latest commit from the `develop` branch and it should be fixed.

**Comment by theSubsurfaceGuy** [comment]
@Deathn0t thank you very much, I appreciate it.
