### ISSUE TITLE
[FAQ] Direct Saving of Model with Best Weights and Biases

### ISSUE THREAD

**Issue by theSubsurfaceGuy** [deephyper/deephyper#198]
The 'results.csv' file conveniently stores all the results, allowing for easy extraction of the best configuration. However, I'm interested to know if it's possible to directly save the trained model, including its optimized weights and biases, without the need for retraining training the model again using the best hyperparameters. Thanks for the insights.

**Comment by Deathn0t** [comment]
Hello @theSubsurfaceGuy , in hyperparameter optimization, the user (you) provides the function to optimize (where the model is trained), in the latest version of DeepHyper, function takes a `RunningJob` object as input

```python
def run(job):
    return job.parameters["x"]
```

this `job` also has a `job.id` which can be used to checkpoint/save your models on the disk with a unique name.

So you can do something like:


```python
def run(job):
   
    # Example saving
    with open(f"{job.id}.txt", "w") as f: pass 

    return job.parameters["x"]
```

If you need more help please specify what is happening inside your `run`-function.

**Comment by theSubsurfaceGuy** [comment]
Hello @Deathn0t, I think your comment was helpful, thank you

**Comment by theSubsurfaceGuy** [comment]
Hello @Deathn0t, I think your comment was helpful, thank you
