### ISSUE TITLE
[BUG] why is cython a dependency?

### ISSUE THREAD

**Issue by haampie** [deephyper/deephyper#215]
**Describe the bug**

`"Cython>=0.29.24"` is in `pyproject.toml`, but where is it used?

**Expected behavior**

No redundant deps

**Comment by Deathn0t** [comment]
Hello @haampie , 

I will have to test/check if this package [ConfigSpace](https://github.com/automl/ConfigSpace/blob/main/pyproject.toml#L87) is now compiling well on Macos without this requirement. I had trouble with it in the past, and `Cython>=0.29.24`  fixed it.

I will test it in the coming days and remove it if possible.

**Comment by haampie** [comment]
So, the point is to put a constraint on a build dep of a dependency? ^^

**Comment by Deathn0t** [comment]
Yes... a quick fix to have `pip install deephyper` work.
