### ISSUE TITLE
[FAQ] How do I use DeepHyper with a job that requires Python multiprocessing?

### ISSUE THREAD

**Issue by davdma** [deephyper/deephyper#216]
**Context**
I am running a model in PyTorch that uses `num_workers=10` for the [dataloader](https://pytorch.org/docs/stable/data.html) to serve up data for training. The worker processes are created and have access to a shared python multiprocessing array that they populate, which allows for quick access to cached data after the first epoch. As a sample, this is part of the dataset class used by the PyTorch dataloader with the shared python multiprocessing Array:

````python
import ctypes
import multiprocessing as mp
class FloodSampleDataset(Dataset):
  def __init__(self, sample_dir, labels_dir, channels=[True] * 9, typ="train", transform=None, random_flip=True, seed=41000, size=64):
          self.sample_dir = sample_dir
          self.labels_dir = labels_dir
          self.labels_path = glob(labels_dir + 'label_*.npy')
          self.channels = channels
          self.typ = typ
          self.transform = transform
          self.random_flip = random_flip
          self.seed = seed
          self.size = size
  
          # cached arrays
          saved_samples_base = mp.Array(ctypes.c_float, len(self.labels_path)*9*size*size)
          saved_samples_array = np.ctypeslib.as_array(saved_samples_base.get_obj())
          saved_samples_array = saved_samples_array.reshape(len(self.labels_path), 9, size, size)
  
          saved_label_base = mp.Array(ctypes.c_uint8, len(self.labels_path)*size*size)
          saved_label_array = np.ctypeslib.as_array(saved_label_base.get_obj())
          saved_label_array = saved_label_array.reshape(len(self.labels_path), 1, size, size)
          
          self.saved_samples = torch.from_numpy(saved_samples_array)
          self.saved_labels = torch.from_numpy(saved_label_array)
          self.use_cache = False
````

However, while the model training loop works on its own in testing, when I run it inside the function of a DeepHyper optimization problem (using a serial evaluator), my model freezes after 2 epochs and I get the following error:

`python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to deadlock. 
self.pid = os.fork()`

I do not get this error when running my model training outside of DeepHyper optimization, so I assume it must be related to something DeepHyper is doing. I also don't get this error when I use `num_workers=0` and running in DeepHyper so it is related to the multiprocessing of PyTorch.

**Describe the task you are trying to achieve.**
My implementation of the PyTorch dataloader is very similar to the solution in [this thread](https://discuss.pytorch.org/t/dataloader-resets-dataset-state/27960), and I want to make it work when run as a job inside of DeepHyper as I am trying to tune my model. Currently there is some weird deadlock situation going on, but I am no expert at multiprocessing so I am not sure what really is happening.

**Describe the solution you'd like**
I would like to know if there is a way for me to make the DeepHyper interface also work with the python multiprocessing array that I am using for my PyTorch model training that does not lead to a deadlock situation.

**Comment by Deathn0t** [comment]
Hello @davdma , 

could please share a simplified reproducible example of the DeepHyper + optimized function you are using?
