### ISSUE TITLE
[FAQ] Why is jinja2 version locked.

### ISSUE THREAD

**Issue by arnold-jr** [deephyper/deephyper#217]
**Context**
Jinja2 seems to be the only dependency which is upper bounded. https://github.com/deephyper/deephyper/blob/739bf6629a1a0681b16996dc8bcf381a6ef4a224/setup.py#L25
Is this intentional?

**Describe the task you are trying to achieve.**
I'm trying to use deephyper as a dependency and have run into version conflicts for jinja2.

**Describe the solution you'd like**
Upper bound restriction on jinja2 version is removed. Code is updated to work around change in functionality, if applicable.

**Comment by arnold-jr** [comment]
Sorry, I see there is a comment regarding a security vulnerability. This [one](https://security.snyk.io/vuln/SNYK-PYTHON-JINJA2-6809379) was fixed in 3.1.4.

**Comment by Deathn0t** [comment]
Hi @arnold-jr , thank you for noticing this, I updated the setup (commit: 567860856775ac41be60c50b2f5984ee3dffdc5e) by forcing `Jinja2>=3.1.4` now.

**Comment by arnold-jr** [comment]
Thank you!
