### ISSUE TITLE
[BUG] Adding warning or exception when Evaluator and Storage types are incompatible

### ISSUE THREAD

**Issue by TheRisenPhoenix** [deephyper/deephyper#218]
**Describe the bug**
Following the [documentation](https://deephyper.readthedocs.io/en/latest/_autosummary/deephyper.stopper.html), I use the following expression in my training loop:
`deephyper_job.record(budget=i+1, objective=last_eval_wins_sum)`
Unfortunately, while executing, I get the following error:

```
  File "/training/trainer.py", line 255, in train
    deephyper_job.record(budget=i+1, objective=last_eval_wins_sum)
  File "/lib/python3.11/site-packages/deephyper/evaluator/_job.py", line 140, in record
    self.stopper.observe(budget, objective)
  File "/lib/python3.11/site-packages/deephyper/stopper/_asha_stopper.py", line 89, in observe
    self.job.storage.store_job_metadata(
  File "/lib/python3.11/site-packages/deephyper/evaluator/storage/_memory_storage.py", line 105, in store_job_metadata
    self._data[search_id]["data"][partial_id]["metadata"][key] = value
    ~~~~~~~~~~^^^^^^^^^^^
KeyError: '0'
```

For initialization, I use this:
```
evaluator = Evaluator.create(train, method="process", method_kwargs={"num_workers": 4})
evaluator.run_function_kwargs = {"cfg": cfg}

stopper = SuccessiveHalvingStopper(min_steps=1, max_steps=100)
search = CBO(problem, evaluator, stopper=stopper, random_state=42)

results = search.search(max_evals=100, timeout=432000)
```

**To Reproduce**
I haven't worked on a reproducable example yet.

**Expected behavior**
No exception.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python version 3.11
 - DeepHyper Version 0.7.0

Assuming that I simply did something wrong, any help or advice would be greatly appreciated :)

**Comment by Deathn0t** [comment]
Thank you @TheRisenPhoenix for raising this issue. As the attached example works, I think this may be related to the creation of the Evaluator outside the `CBO` object. The `search_id` was therefore not created. I will come back to you soon with an example or a fix.

[example.py.zip](https://github.com/user-attachments/files/15900878/example.py.zip)

**Comment by TheRisenPhoenix** [comment]
Hey there!
Thanks for your quick reply and effort in fixing this! 😊

I did a bit more investigation and it seems like this issue only appears in combination with non-serial execution. When I run my code using a serial worker, it appears to be working fine. 

I also adjusted the example from the [documentation](https://deephyper.readthedocs.io/en/latest/examples/plot_from_serial_to_parallel_hyperparameter_search.html) concerning parallel execution, and added a stopper there. Same here, in the serial version it seems to run, in the parallel version not. 
I hope this helps in identifying the issue?

```python
from deephyper.stopper import SuccessiveHalvingStopper
from deephyper.problem import HpProblem

import time
import numpy as np
from deephyper.evaluator import profile


def ackley(x, a=20, b=0.2, c=2 * np.pi):
    d = len(x)
    s1 = np.sum(x**2)
    s2 = np.sum(np.cos(c * x))
    term1 = -a * np.exp(-b * np.sqrt(s1 / d))
    term2 = -np.exp(s2 / d)
    y = term1 + term2 + a + np.exp(1)
    return y


@profile
def run_ackley(config, sleep_loc=2, sleep_scale=0.5):

    # to simulate the computation of an expensive black-box
    if sleep_loc > 0:
        t_sleep = np.random.normal(loc=sleep_loc, scale=sleep_scale)
        t_sleep = max(t_sleep, 0)
        time.sleep(t_sleep)

    x = np.array([config[k] for k in config if "x" in k])
    x = np.asarray_chkfinite(x)  # ValueError if any NaN or Inf
    config.record(budget=i+1, objective=-ackley(x))
    return -ackley(x)  # maximisation is performed


if __name__ == "__main__":
    from deephyper.evaluator import Evaluator
    from deephyper.evaluator.callback import TqdmCallback
    from deephyper.search.hps import CBO

    nb_dim = 2
    problem = HpProblem()
    for i in range(nb_dim):
        problem.add_hyperparameter((-32.768, 32.768), f"x{i}")

    # we give a budget of 2 minutes for each search
    timeout = 12
    serial_evaluator = Evaluator.create(
        run_ackley,
        method="serial",
        method_kwargs={"callbacks": [TqdmCallback()]},
    )
    print("Running serial search...")
    results = {}
    stopper = SuccessiveHalvingStopper(min_steps=1, max_steps=10)
    serial_search = CBO(problem, serial_evaluator, stopper=stopper, random_state=42)
    results["serial"] = serial_search.search(timeout=timeout)
    results["serial"]["m:timestamp_end"] = (
        results["serial"]["m:timestamp_end"]
        - results["serial"]["m:timestamp_start"].iloc[0]
    )

    parallel_evaluator = Evaluator.create(
        run_ackley,
        method="process",
        method_kwargs={"num_workers": 1, "callbacks": [TqdmCallback()]},
    )
    print("Running parallel search...")
    stopper = SuccessiveHalvingStopper(min_steps=1, max_steps=10)
    parallel_search = CBO(problem, parallel_evaluator, stopper=stopper, random_state=42)
    results["parallel"] = parallel_search.search(timeout=timeout)
    results["parallel"]["m:timestamp_end"] = (
        results["parallel"]["m:timestamp_end"]
        - results["parallel"]["m:timestamp_start"].iloc[0]
    )

```

**Comment by Deathn0t** [comment]
Okay. I have it! It is actually not a mistake. Let me explain. By default, a `MemoryStorage` is used and this corresponds to local memory of the process, therefore this memory is not shared between processes (workers). If you want to use `method="process"` you would have to use the `RedisStorage` and start a Redis database before that.
But, you can try using the `method="ray"` if you have installed the Ray dependencies `pip install deephyper['ray']`. This with use a memory space that can be shared with ray processes.

**Comment by TheRisenPhoenix** [comment]
Thanks for the clarification!
I may have missed a reference to this in the documentation. However, perhaps a preliminary check of the combination of the method and the default memory storage might prevent the error message and thus be less confusing? 
Anyway, thanks for the explanation, I really appreciate your help and also your work on the library! :smiley:

**Comment by Deathn0t** [comment]
Hello @TheRisenPhoenix , 

Definitely! I agree with the checks and improved documentation. Would you like to help with that? I can help you figure out where to edit the code. I will probably be able to look at this by the end of the month personally. We have a slack workspace if you would like to join it.

I am very sorry for the delay in my reply. I was away for a few weeks.

**Comment by TheRisenPhoenix** [comment]
Hi there!
I really appreciate the offer, but unfortunately I too am too busy at the moment. 
However, I'm really grateful for your efforts in maintaining an open source library, this is so valuable for many people! Thanks a lot for that and also for your support with my question! :)

**Comment by Deathn0t** [comment]
The issue was resolved by now providing a new `SharedStorage` for `"process"` evaluator. See https://github.com/deephyper/deephyper/blob/develop/src/deephyper/evaluator/_process_pool.py#L41
