### ISSUE TITLE
[FAQ] Workload distribution question

### ISSUE THREAD

**Issue by jinz2014** [deephyper/deephyper#222]
Could you please provide some examples for workload distribution ?   Thanks.

Distribute tasks across multiple GPUs in a node ?

Distribute tasks across multiple nodes and each node has multiple GPUs ?

Each task is executed independently from other tasks.

**Comment by Deathn0t** [comment]
Hello @jinz2014 , sorry for the delay I was out of the office.

For that, we use `MPICommEvaluator` in DeepHyper. The idea is the script launching deephyper is called with`mpirun/mpiexec/srun` or some other variant. Then the rank 0 will be the master and other ranks are workers. So, you can just place the ranks however you prefer using the arguments for the MPI command. The simplest case assumes GPUs are spread evenly across ranks (e.g., `N` GPUs per rank).

The only think to be careful about is to know if your MPI commands automatically set the GPU environment variable or not. For example, `srun` from slurm automatically set the `CUDA_VISIBLE_DEVICES`. If that's not the case you can do it yourself by setting the variable withing the python script by checking the `rank % num_gpus_per_node`.


An example of how the MPI commands call the script: https://github.com/deephyper/scalable-bo/blob/main/experiments/polaris/dhb/dhb_combo-CBO-DUMMY-UCB-10-10800.sh

The same example where the `Evaluator` and the search are created: https://github.com/deephyper/scalable-bo/blob/main/src/scalbo/scalbo/search/cbo.py#L135


Let me know if you need more help. Do not hesitate to share your scripts in the thread.
