### ISSUE TITLE
Transition package setup to toml

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/deephyper#231]
- [x] add`install_requires` of current `setup.py` to `pyproject.toml`.
- [x] add `extras_require` of current `setup.py` to `pyproject.toml` but ignore `EXTRAS["default"]`.
- [x] add `ruff` configuration to `pyproject.toml`.
- [x] add `pytest.ini` to `pyproject.toml`.
- [x] suggest a way to replace the current `Command`s of the `setup.py`
- [ ] consider updating coverage execution
- [x] replace steps 9-11 on [documentation page](https://deephyper.readthedocs.io/en/latest/developer_guides/build_and_release.html) with [source file](https://github.com/deephyper/deephyper/blob/develop/docs/developer_guides/build_and_release.rst)

**Comment by wigging** [comment]
The recent pull request fixes most of the items mentioned in this issue. The ruff configuration will be handled in a separate pull request which is also discussed in another issue. The coverage execution will be handled in another pull request too.

**Comment by wigging** [comment]
Ruff configuration has been completed in a recent pull request.
