### ISSUE TITLE
Check docstrings with ruff to improve code documentation

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/deephyper#232]
Using ruff, we will check the docstrings of the public code. If docstrings are not present or do not follow "google style" then it will raise an error and fail the test.

**Comment by wigging** [comment]
This is can be enabled in the pyproject.toml file using the ruff lint configuration. See the [ruff docs](https://docs.astral.sh/ruff/settings/#lintpydocstyle) for more info.

**Comment by wigging** [comment]
Here are the pydocstyle rules used by ruff for checking docstrings:
https://docs.astral.sh/ruff/rules/#pep8-naming-n

**Comment by Deathn0t** [comment]
Processing ruff checks with linelength=100:

- [ ] `deephyper.analysis` @Deathn0t 
- [ ] `deephyper.core` @wigging 
- [ ] `deephyper.ensemble` @Deathn0t 
- [ ] `deephyper.evaluator` @wigging 
- [ ] `deephyper.hpo` @Deathn0t 
- [ ] `deephyper.predictor` @wigging 
- [x] `deephyper.skopt` (IGNORED for now)
- [ ] `deephyper.stopper` @Deathn0t
