### ISSUE TITLE
Unable to execute deephyper command from Linux terminal

### ISSUE THREAD

**Issue by sibyjackgrove** [deephyper/deephyper#26]
I pip installed deephyper on a Linux server. However, I getting the following error when I try to run a HPS using `deephyper hps ambs --problem problem.Problem --run model_run.run`
I get the following error:
> bash: deephyper: command not found

Hardware arch: x86_64
Server CPU: Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
OS: 18.04.2-Ubuntu

Python version: 3.7.5
TensorFlow version: 1.14  (tried with 2.0 as well with the same result)

Please suggest a solution.

**Comment by Deathn0t** [comment]
Hi @sibyjackgrove ,

Did you try to open the python shell, and import deephyper to check if the installation is well finished? Such as:
```bash
$ python
```
then
```python
>>> import deephyper
```
otherwise you can try:
```bash
python -m deephyper.search.hps.ambs --problem problem.Problem --run model_run.run
```

**Comment by sibyjackgrove** [comment]
Yes, import deephyper in Python shell did not show any error.  However `python -m deephyper.search.hps.ambs` did work. Thanks for the help.
