### ISSUE TITLE
AddByProjecting axis argument

### ISSUE THREAD

**Issue by Romit-Maulik** [deephyper/deephyper#29]
The current [AddByProjecting](https://github.com/deephyper/deephyper/blob/8293621e069b15176568c3491f069f3684b85f56/deephyper/search/nas/model/space/op/merge.py#L137) operation does not have an option for the axis of projection. This would be beneficial for LSTM/CNN type operations involving skip connections. 

I suggest the following update to the `__init__`
```
    def __init__(self, search_space, stacked_nodes=None, activation=None, axis=-1):
        self.search_space = search_space
        self.node = None # current_node of the operation
        self.stacked_nodes = stacked_nodes
        self.activation = activation
        self.axis = axis
```
and the following update to [this](https://github.com/deephyper/deephyper/blob/8293621e069b15176568c3491f069f3684b85f56/deephyper/search/nas/model/space/op/merge.py#L174) line
`proj_size = values[0].get_shape()[self.axis]`

With these, I am able to make search spaces of LSTMs as shown in the attachment
![sampled_neural_network](https://user-images.githubusercontent.com/12647892/74673917-d7b1d200-5175-11ea-8666-398d64a94f14.png)

**Comment by Deathn0t** [comment]
resolved in 31cb506eb99d61839316130148d1074488b112b5
