### ISSUE TITLE
AssertionError in AMBS optimization when there are no continuous hyperparameters

### ISSUE THREAD

**Issue by masalim2** [deephyper/deephyper#3]
Bethany ran a custom hps search resulting in 
```
File "/Users/blusch/Documents/deephyper/deephyper/deephyper/search/optimizers/optimizer.py", line 91, in tell
    assert len(XX) == len(YY) == self.counter
AssertionError
```

[deephyper.log](https://github.com/deephyper/deephyper/files/2742624/deephyper.log)

This invariant seems to break only after the first repeated evaluation; which makes sense because this code path was not exercised in prior AMBS experiments that always had at least one continuous h.p.  In this case, all h.p. are discrete which causes repeat evaluations near convergence.

**Comment by Deathn0t** [comment]
@masalim2 is it really related with discrete h.p. or can that happen with continuous h.p. as well but it's more "difficult" ?

**Comment by masalim2** [comment]
I think it’s much more likely with discrete h.p; at least I have never seen it happen after probably tens of thousands of AMBS evaluations with some other benchmarks

On Jan 11, 2019, at 9:50 AM, Romain Egele <notifications@github.com<mailto:notifications@github.com>> wrote:


@masalim2<https://github.com/masalim2> is it really related with discrete h.p. or can that happen with continuous h.p. as well but it's more "difficult" ?

**Comment by masalim2** [comment]
Issue is due to the fact that the Optimizer stores a copy of the evals in a dict mapping {hps : objective}.  When a duplicate hps value is passed on optimizer.tell() the dict entry is overwritten.  However, on optimizer.ask(),  the counter is incremented by the total number of returned hps values, even if some are duplicates.  This breaks the invariant between ask() & tell() calls.  Can fix either by removing optimizer.counter value, or incrementing the counter by number of *unique* and *unevaluated* hps values.

**Comment by Deathn0t** [comment]
I think the second option is better: "or incrementing the counter by number of unique and unevaluated hps values" because we could use it to collect statistics from the run and have some analysis.
