### ISSUE TITLE
Add ability to log output quantities other than the objective

### ISSUE THREAD

**Issue by felker** [deephyper/deephyper#31]
The objective of a problem is defined by the return value of `run()`. As far as I know, this is the only way that a quantity other than the search space dimensions will ever be logged to `results.csv` by the evaluators. 

It might be useful to track other output metrics that are not directly optimized by the search algorithm. I could envision a counterpart to:
https://github.com/deephyper/deephyper/blob/ac31d5465938b7cc33558e4d18575cb69363b2ef/deephyper/benchmark/problem.py#L23-L30

e.g. `add_output(out_name)` that defines a dictionary key that could be written to inside `run()`.

If there is already a convenient way to do this inside DH, please let me know

**Comment by Deathn0t** [comment]
Right now there is not any ways of tracking other values than the output of the run function for the `results.csv`.  I personally dump small jsons during the execution of `run()` to be able to log whatever I want even if it doesn't fit in the csv such as the loss trajectory. We could absolutely try to find a better way to log, collect and store information in DeepHyper. I even think it is something really important to not lose the information we could later use to apply some meta-learning algorithm and extract knowledge from DeepHyper...

**Comment by Deathn0t** [comment]
Maybe this feature could be handled by some evaluators such as the ray evaluator where returning many features is very easy.

**Comment by Deathn0t** [comment]
A dict containing one key named `objective` can be returned with other information. (`deephyper==0.4.0`)
