### ISSUE TITLE
Installation error. Can't find the specified version of tensorflow.

### ISSUE THREAD

**Issue by Viren-C** [deephyper/deephyper#33]
I am using python 3.8 with pip 20.0.2
`ERROR: Could not find a version that satisfies the requirement tensorflow<=1.15.2,>=1.13.1 (from deephyper==0.1.7) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3)
ERROR: No matching distribution found for tensorflow<=1.15.2,>=1.13.1 (from deephyper==0.1.7)`

**Comment by Deathn0t** [comment]
Hello @Viren-C could I have more information about the way you tried to install DeepHyper:
* what environment where you using?
* what procedure did you follow to install DeepHyper?
* did you have an already existing tensorflow version?
* does your current environment allow for installing tensorflow between 1.13 and 1.15?

**Comment by Viren-C** [comment]
- I am using fresh empty environment. 
- I tried installing using pip and through github and still got the same error. 
- No, the environment in which i am working has no version of tensorflow.
-  My current environment has no restrictions for any installations

**Comment by Deathn0t** [comment]
I managed to reproduce your error, and apparently Tensorflow 1.13 to 1.15 are not available with python 3.8. A possible fixe is to use `conda` to create a virtual environment under python 3.7 such as:
```console
$ conda create -n dh-env python=3.7
```
