### ISSUE TITLE
Issue with relative "Problem" import in HPS demo

### ISSUE THREAD

**Issue by tjburch** [deephyper/deephyper#36]
I've been working through the [HPS demo](https://deephyper.readthedocs.io/en/latest/tutorials/hps.html#running-the-search-on-alcf-s-theta-and-cooley) and have run into an issue with the relative imports trying to run the scan. Executing

```
deephyper hps ambs --problem polynome2.problem.Problem --run polynome2.model_run.run
```

Throws: ```ModuleNotFoundError: No module named 'polynome2'```

I can, however, get the HPS to run if I instead give the explicit full path:

```
deephyper hps ambs --problem $(PATH_TO_DEMO)/demo/demo/polynome2/problem.py --run $(PATH_TO_DEMO)/demo/demo/polynome2/model_run.py
```

Hopefully this isn't something obvious I'm missing, I didn't see any other issues or notes raised on this. Thanks!

----
Full traceback:

```
Uncaught exception <class 'deephyper.core.exceptions.loading.GenericLoaderError'>: Traceback (most recent call last):
  File "/gpfs/mira-home/tburch/dh-env/lib/python3.7/site-packages/deephyper/search/util.py", line 164, in generic_loader
    attr = load_attr_from(target)
  File "/gpfs/mira-home/tburch/dh-env/lib/python3.7/site-packages/deephyper/search/util.py", line 124, in load_attr_from
    module = importlib.import_module(str_module)
  File "/gpfs/mira-home/tburch/dh-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
```

**Comment by Deathn0t** [comment]
Hello @tjburch, I noticed the documentation was slightly inconsistent. When you execute `deephyper start-project hps_demo` it creates a folder containing a Python package called `hps_demo`, the structure of the folder is the following:

```
hps_demo/
    hps_demo/
         __init__.py
        polynome2/
            __init__.py
            load_data.py
            model_run.py
            problem.py
    setup.py
```

Also the command `start-project` is installing this package in your current Python environment. Hence if you start a python shell you can do `import hps_demo`.

After creating this package you have to move to the root directory of this package which is `hps_demo/hps_demo/`. Once you are in this folder you can execute `deephyper new-problem hps polynome2`.

You can now submit the task with:

```console
$ deephyper balsam-submit hps polynome2_demo -p hps_demo.polynome2.problem.Problem -r hps_demo.polynome2.model_run.run  -t 30 -q debug-cache-quad -n 4 -A datascience -j mpi
```
The [documentation](https://deephyper.readthedocs.io/en/latest/tutorials/hps.html#running-the-search-on-alcf-s-theta-and-cooley) was updated according to these explanations.

**Comment by tjburch** [comment]
Thanks @Deathn0t!
