### ISSUE TITLE
DeepHyper on TensorFlow 2 & GPUs

### ISSUE THREAD

**Issue by ekourlit** [deephyper/deephyper#38]
Hi, 

I have cloned DH from git and changed the `setup.py` to point it to TF2.2.0-GPU.
I 'm working on an HPS so I developed my `model_run.py` which when I test with a command like:
```bash
python model_run.py
```
I get the expected behavior, TF is using my machine GPU(s) to train the model. However, when I run my `run()` function with DH:
```bash
deephyper hps ambs --problem <myProblem> --run <myRun>
```
TF is not seeing the GPUs:
```
failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
```
and the training proceeds on my CPU.

Have you faced any similar issue before? Or DH makes a call to TF that prohibit it to see the GPUs?

Thanks in advance!
Vangelis

**Comment by Deathn0t** [comment]
Hi @ekourlit , 

I never got into this issue but I have a few ideas about it...

### First solution

In DeepHyper, we developed the `Evaluator` API ([link to code](https://github.com/deephyper/deephyper/tree/master/deephyper/evaluator)) to abstract how the work is distributed. By default, the `--evaluator ray` is used. It is probable that this backend needs a specific argument to recognize local GPUs ([GPU Support with Ray](https://docs.ray.io/en/master/using-ray-with-gpus.html?highlight=GPU)) and then you would probably need to modify [this line](https://github.com/deephyper/deephyper/blob/master/deephyper/evaluator/ray_evaluator.py#L14) to `@ray.remote(num_gpus=N)` where `N` is the number of GPUs.


### Second solution

Another solution that should directly work if you use DeepHyper on a single machine is ot use the Subprocess evaluator by giving the `--evaluator subprocess` argument to the command line.

Let me know how it goes and if you find a way to implement this option in a nice manner feel free to create a Pull Request!

**Comment by ekourlit** [comment]
Hi @Deathn0t ,

thanks for your reply! Your first solution worked well for me and after configuring Ray to see the GPUs I'm able to use use them for training the NNs of my HPS. The machine I'm using though it's quite of a custom setup (3 GPUs which only 2 of them I can use) so I had to correctly set the `CUDA_VISIBLE_DEVICES` environmental variable too, so unfortunately I don't have a general implementation of it.

I have another Ray question thoug: Could I use its technology to parallelize the HPS on a single machine? For example, if I switch back to the CPU usage, can the different Ray tasks run on the different cores or threads of my CPU in parallel? At the moment, Ray is creating 24 tasks (as many as my CPU threads) but only one is actually running, the rest are IDLE.

**Comment by Deathn0t** [comment]
Glad to know it worked! In order to keep track of the different issues/questions, I will create a new thread for the Ray question.
