### ISSUE TITLE
[BUG] GPU memory overload 

### ISSUE THREAD

**Issue by ekourlit** [deephyper/deephyper#41]
**Describe the bug**
When performing a HPS on multiple GPUs (i.e. 1 Ray task per GPU), after each model training & evaluation the memory is not flushed. As an effect, in each HPS-point the GPU memory accumulates. Eventually, the user will end up without any memory left before the HPS converge.

**To Reproduce**
1. Use `tensorflow-gpu`.
2. Initialize as many Ray tasks as your GPUs. Described [here](https://github.com/deephyper/deephyper/issues/40#issuecomment-647345882), but use `GPU` instead of `CPU`.
3. On your `model_run.py` configure a dynamic GPU memory allocation by using `tf.config.experimental.set_memory_growth` as described [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth).
4. You should be ready! Execute your GPU-based HPS with:
```
deephyper hps ambs --problem <myProblem> --run <myRun>
```

**Expected behavior**
I would expect after each HPS-point training & evaluation the GPU memory to be flushed. In this way I could run as many HPS-points as needed without accumulating the memory load of the previous point.

**Desktop:**
 - OS: Ubuntu 18.04.4 LTS
 - System: Local machine
 - Python version: 3.7.7
 - DeepHyper Version: 0.1.11
 - TensorFlow Version: 2.2.0 (GPU)

**Additional context**
This is a follow up of the issue #40. After some web investigation, the problem seems to be related with the TensorFlow behavior and is reported [here](https://github.com/tensorflow/tensorflow/issues/36465).
I tried the solution using `multiprocessing` proposed [here](https://github.com/tensorflow/tensorflow/issues/36465#issuecomment-582749350) but it didn't work for me. I get the error:
```
E tensorflow/stream_executor/cuda/cuda_driver.cc:1045] failed to enqueue async memcpy from host to device: CUDA_ERROR_NOT_INITIALIZED: initialization error; GPU dst: 0x7f7f63000d00; host src: 0x5614a238a040; size: 8=0x8
```
I note however, people are commenting that the solution is not working for TF 2.2 on RTX cards, which is exactly my setup. It would be great if someone can cross-check in different cards.

**Comment by Deathn0t** [comment]
Hello @ekourlit ,

Coming back to this issue because I am now using Ray in the same context.
By any chance, did you try the `max_calls=1` fix? I found it on the [Ray documentation](https://docs.ray.io/en/master/using-ray-with-gpus.html)

```python
import tensorflow as tf

@ray.remote(num_gpus=1, max_calls=1)
def leak_gpus():
    # This task will allocate memory on the GPU and then never release it, so
    # we include the max_calls argument to kill the worker and release the
    # resources.
    sess = tf.Session()
```

**Comment by ekourlit** [comment]
Hi! Thanks for getting back to this! I never tried this solution but the documentation seem to describe and troubleshoot this exact problem. I will definitely try it at some point.

**Comment by Deathn0t** [comment]
To resolve the OOM error in my case I had to combine two things, the `max_calls` argument in the remote function as well as activating memory growth for GPU memory allocation with Tensorflow:

```python
import tensorflow as tf

@ray.remote(num_gpus=1, max_calls=1)
def leak_gpus():
    # This task will allocate memory on the GPU and then never release it, so
    # we include the max_calls argument to kill the worker and release the
    # resources.
    physical_devices = tf.config.list_physical_devices("GPU")
    try:
        for i in range(len(physical_devices)):
            tf.config.experimental.set_memory_growth(physical_devices[i], True)
    except:
        # Invalid device or cannot modify virtual devices once initialized.
        pass

  ... # CODE TO RUN
```

I will consider this issue as resolved. Please reopen if necessary.
