### ISSUE TITLE
DeepHyper with TF 2.0

### ISSUE THREAD

**Issue by ticlazau** [deephyper/deephyper#48]
Hello,

I will like to know if it's possible to get DeepHyper support for TensorFlow 2.x

Thx,
FM

**Comment by Deathn0t** [comment]
Hello @ticlazau,

It depends on which features you are interested in. If you are interested in hyperparameter search, you can use this branch: https://github.com/deephyper/deephyper/tree/feature/tensorflow2.
However, if you are interested in neural architecture search the support is not ready for TF 2.X.

We aim at bringing TF 2.X but I can't give you an exact date for now. All contributions are welcome if you are interested in submitting some pull requests (I can also help you understand the structure of the software of course to ease the task).

I hope this will answer your question.
Best regards, Romain.

**Comment by ticlazau** [comment]
Thank you @Deathn0t 
Right now I am looking for a hyperparameters search, so is all good.
