### ISSUE TITLE
[BUG] Deephyper and Ray Cluster using GPUs on Cori

### ISSUE THREAD

**Issue by papajim** [deephyper/deephyper#53]
**Describe the bug**
I'm facing an issue when I try to start deephyper running on ray cluster and allocating GPUs on Cori (NERSC).
I'm using Tuster to deploy everything but when Tuster (most likely) attempts to submit the job with srun then I receive the following error on the --gres argument.

srun: error: Unable to create step for job X: Invalid generic resource (gres) specification

This is the sbatch script I'm submitting: [Run_Batch_Ray_Bepop_GPU.zip](https://github.com/deephyper/deephyper/files/5923233/Run_Batch_Ray_Bepop_GPU.zip)

**To Reproduce**
module load cgpu
sbatch Run_Batch_Ray_Bepop_GPU.sh

**Desktop (please complete the following information):**
 - System: Cori dev with GPUs
 - Python version: 3.7.4
 - DeepHyper Version: 0.2.1
 - Tuster version: 0.0.1
 - Ray version: 0.7.6

Could you please point me to where I should look to debug and resolve this issue?

**Comment by Deathn0t** [comment]
Hello @papajim , thanks for reporting this bug. 
Could you please share with me the Tuster version you are using? I think you may use a "private" version that I don't know about because the "bebop" system was not pushed to [the official repo](https://github.com/ytopt-team/tuster)

**Comment by papajim** [comment]
Hello @Deathn0t!

I have attached the tuster repo I'm using.
[tuster.tar.gz](https://github.com/deephyper/deephyper/files/5927163/tuster.tar.gz)

**Comment by Deathn0t** [comment]
I found an explanation about the error you mentioned  [here](https://slurm-dev.schedmd.narkive.com/nDK4Ixsp/srun-error-unable-to-create-job-step-invalid-generic-resource-gres-specification):

> When srun is executed within an existing allocation (salloc or
sbatch), it starts a job step that can only use resources already
allocated to that job (no GPUs in the job then you can't get them from
a job step).

Maybe [this tutorial](https://slurm.schedmd.com/quickstart.html) can help us figuring out what is happening. How, do you submit the script `Run_Batch_Ray_Bebop_GPU.sh` ?

**Comment by Deathn0t** [comment]
Maybe the issue is coming from:

```bash
#SBATCH --cpus-per-task=20
#SBATCH --gpus-per-task=1
``

and 

```bash
srun -n 2 python...
```

If there is only one GPU per task, it looks the the `srun` is asking for 2 tasks?

**Comment by papajim** [comment]
Removing these constraints seems to have fixed this issue.
However it doesn't fully make sense since I was explicitly acquiring 2 GPUs (#SBATCH -G 2).

I probably need to ask NERSC support about this...

Could you please point me to the section that Tuster deploys the actual application?

**Comment by Deathn0t** [comment]
So In your bash script you call

```bash
srun -n 2 python -m tuster.system.bebop.run 'python -m deephyper.search.hps.ambs --evaluator ray --redis-address {redis_address} --acq-func LCB --kappa 7 --problem DAIN_KMNIST.problem.Problem --run DAIN_KMNIST.model_run.run'
```

which will execute the script located in the tuster package at `tuster/system/bebop/run`

this script is going to start Ray daemons and your nodes and then the application here deephyper which will connect to this Ray daemons. So you may have to edit the way the cluster is launched based on your system. This one was made for Bebop apparently.

**Comment by papajim** [comment]
Ok thank you!
I will take a look :)
