### ISSUE TITLE
Update documentation for NAS Analytics on Theta

### ISSUE THREAD

**Issue by Romit-Maulik** [deephyper/deephyper#55]
Currently, [documentation](https://deephyper.readthedocs.io/en/latest/tutorials/nas.html) only has the following code snippet for analytics
```
deephyper-analytics json -h
usage: deephyper-analytics json [-h] {best} ...
positional arguments:
{best}      Kind of analytics.
    best      Select the best n search_spaces and save them into a JSON file.
```

when we need something like 
```
deephyper-analytics json best -n 100 -p json_file_name.json
```
This may confuse new users. 

Another issue is this command
```
deephyper-analytics parse deephyper.log
```
should be replaced with 
```
deephyper-analytics parse $(pwd)/deephyper.log
```
and it should be ensured that the Balsam database is active before running it as well to compute the workload appropriately.

**Comment by Deathn0t** [comment]
A warning should be printed if the Balsam database is not connected. However, not all features of DeepHyper use Balsam therefore the process can still be performed even if no Balsam database is connected.

The `deephyper-analytics` command line was updated to improve the coherence of the different tools.
Additionnal documentation is provided at https://deephyper.readthedocs.io/en/develop/software/analytics.html
It will be added in the next release of DeepHyper.
