### ISSUE TITLE
use gpu

### ISSUE THREAD

**Issue by ml-rakesh** [deephyper/deephyper#67]
hi @Deathn0t 
how can I use gpu while searching for network in deephyper?

**Comment by Deathn0t** [comment]
Hello @ml-rakesh, 

If your installation has NVIDIA libraries for Deep Learning the installed tensorflow should directly be able to use the GPU for each training.

**Comment by ml-rakesh** [comment]
Hello @Deathn0t 

tensorflow version : '2.1.3'

yeah i installed nvidia library, but while looking for gpu it was only showing cpu as a physical device.

**Comment by Deathn0t** [comment]
Do you manage to just install Tensorflow in your python environment and detect the GPU?

**Comment by ml-rakesh** [comment]
hello @Deathn0t 
yeah I installed Tensorflow but I can not detect GPU as a physical device.

**Comment by Deathn0t** [comment]
a few things that can help:

1. if you can use `conda` to install tensorflow-gpu with: `conda install tensorflow-gpu`
2. make sure the CUDA libraries are accessible in the `LD_LIBRARY_PATH` such as `cudnn`
