### ISSUE TITLE
Installation instruction on theta

### ISSUE THREAD

**Issue by jke513** [deephyper/deephyper#69]
**Describe the bug**
Deephyper version is 0.2.2 rather than 0.2.4 by following the installation instruction on theta: https://deephyper.readthedocs.io/en/latest/install/theta.html 
  
**To Reproduce**
```
module load postgresql
module load miniconda-3
conda create -p dh-theta python=3.8 -y
conda activate dh-theta/
conda install gxx_linux-64 gcc_linux-64 -y
pip install deephyper[analytics,balsam]
conda install tensorflow -c intel -y
```

**Expected behavior**
Checked version after installation,
> (miniconda-3/latest/base) jkoo@thetalogin5:/lus/theta-fs0/projects/OptADDN/hepnos/run/env21/run/exp_run_62> source activate /lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta
> (miniconda-3/latest//lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta) jkoo@thetalogin5:/lus/theta-fs0/projects/OptADDN/hepnos/run/env21/run/exp_run_62>
> (miniconda-3/latest//lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta) jkoo@thetalogin5:/lus/theta-fs0/projects/OptADDN/hepnos/run/env21/run/exp_run_62> ipython
```
Python 3.8.8 (default, Apr 13 2021, 19:58:26)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deephyper as dh

In [2]: print (dh.__version__)
0.2.2
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - System: [Theta]
 - Python version [3.8]
 - DeepHyper Version [0.2.2]

**Additional context**
Ray with 1.3.0 is installed.

**Comment by Deathn0t** [comment]
try `pip install deephyper --upgrade`

**Comment by jke513** [comment]
Thank you for your suggestion. `pip install deephyper --upgrade` leads to 0.2.4, though dependency conflicts for tenforflow. I think this comes from `conda install tensorflow -c intel -y`  

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
intel-tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.19.4 which is incompatible.
intel-tensorflow 2.3.0 requires scipy==1.4.1, but you have scipy 1.6.3 which is incompatible.
intel-tensorflow 2.3.0 requires tensorflow-estimator<2.4.0,>=2.3.0, but you have tensorflow-estimator 2.4.0 which is incompatible.
Successfully installed deephyper-0.2.4 grpcio-1.32.0 numpy-1.19.4
(miniconda-3/latest//lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta) jkoo@thetalogin6:/lus/theta-fs0/projects/OptADDN/hepnos> ipython
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deephyper as dh

In [2]: print (dh.__version__)
0.2.4
