### ISSUE TITLE
Benchmarks should load their data automatically

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/deephyper#7]
Some benchmarks like `deephyper.benchmark.hps.b2` are not checking if data are already loaded locally and if not download them. Benchmarks are here for different kind of tests: software testing, efficiency of algorithms...etc.

**Comment by donsmj** [comment]
I have the same issue. When shifted to the b2 , it does not work for me as well.

**Comment by Deathn0t** [comment]
outdated
