### ISSUE TITLE
[BUG] OSError: [Errno 98] Address already in use by Ray evaluator

### ISSUE THREAD

**Issue by jke513** [deephyper/deephyper#70]
**Describe the bug**
Ray evaluator on 128 nodes on theta gives "OSError: [Errno 98] Address already in use"

**To Reproduce**
in job_run.sh,
deephyper hps ambs --evaluator ray --problem hps_2.hepnos.problem_v3.Problem --run hps_2.hepnos.model_run_v3.run --num-workers 32 

qsub -n 128 -t 60 -A OptADDN job_run.sh

**Expected behavior**
The following is the error message. 

> [2m[33m(raylet)[0m /lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py:57: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
> [2m[33m(raylet)[0m   warnings.warn(
> 2021-05-13 20:26:22,835	WARNING worker.py:1115 -- The agent on node thetamom2 failed with the following error:
> Traceback (most recent call last):
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 326, in <module>
>     loop.run_until_complete(agent.run())
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 138, in run
>     modules = self._load_modules()
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 92, in _load_modules
>     c = cls(self)
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 148, in __init__
>     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/ray/_private/metrics_agent.py", line 74, in __init__
>     prometheus_exporter.new_stats_exporter(
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 333, in new_stats_exporter
>     exporter = PrometheusStatsExporter(
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 266, in __init__
>     self.serve_http()
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 320, in serve_http
>     start_http_server(
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/site-packages/prometheus_client/exposition.py", line 149, in start_wsgi_server
>     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/wsgiref/simple_server.py", line 154, in make_server
>     server = server_class((host, port), handler_class)
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/socketserver.py", line 452, in __init__
>     self.server_bind()
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/wsgiref/simple_server.py", line 50, in server_bind
>     HTTPServer.server_bind(self)
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/http/server.py", line 138, in server_bind
>     socketserver.TCPServer.server_bind(self)
>   File "/lus/theta-fs0/projects/OptADDN/hepnos/sw/dh-theta/lib/python3.8/socketserver.py", line 466, in server_bind
>     self.socket.bind(self.server_address)
> OSError: [Errno 98] Address already in use

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - System: [Theta]
 - Python version [3.8]
 - DeepHyper Version [0.2.2]

**Additional context**
Ray with 1.3.0 is installed. 
It happened when it was run on the default queue (nodes > 128), but it did not happen on a debug queue.

**Comment by jke513** [comment]
@Deathn0t, have you seen this error?

**Comment by Deathn0t** [comment]
How did you start the ray cluster?

**Comment by Deathn0t** [comment]
any follow-up with this issue @jke513 ?
