### ISSUE TITLE
[BUG] TensorFlow Probability does not pin necessaryTensorFlow version

### ISSUE THREAD

**Issue by felker** [deephyper/deephyper#77]
This isnt an issue with DeepHyper, per se. But installing DeepHyper with the current `setup.py` can lead to an unworkable environment.

From https://raw.githubusercontent.com/tensorflow/probability/master/README.md
> Note: Since [TensorFlow](https://www.tensorflow.org/install) is *not* included
as a dependency of the TensorFlow Probability package (in `setup.py`), you must
explicitly install the TensorFlow package (`tensorflow` or `tensorflow-cpu`).

https://www.tensorflow.org/probability/install
> TensorFlow Probability depends on a recent stable release of TensorFlow (pip package tensorflow). See the TFP release notes for details about dependencies between TensorFlow and TensorFlow Probability.

So `setup.py` should be edited to 
```
    "tensorflow~=2.4.2",
    "tensorflow_probability~=0.12.2",
```
or 
```
    "tensorflow~=2.5.0",
    "tensorflow_probability~=0.13.0",
```

Otherwise you get an error similar to the following when trying to run DeepHyper:
```
**ImportError: This version of TensorFlow Probability requires TensorFlow version ~= XXX; Detected an installation of version XXX. Please upgrade TensorFlow to proceed.
```

**Comment by Deathn0t** [comment]
Thank you for reporting this @felker, maybe we should move to the most recent versions for the next release.

```python
"tensorflow~=2.5.0",
"tensorflow_probability~=0.13.0",
```

**Comment by Deathn0t** [comment]
I integrated this change on the `develop` branch: https://github.com/deephyper/deephyper/blob/develop/setup.py#L41
