### ISSUE TITLE
[FEATURE] Remove dependency on external Keras

### ISSUE THREAD

**Issue by felker** [deephyper/deephyper#88]
Is there a specific reason why Keras is still a dependency in `setup.py`? Why not just use `tf.keras`?

After a quick glance, I could only find a couple of files that reference standalone Keras:
```
./benchmark/util.py
./benchmark/hps/cifar10cnn/data/get_data.py
./benchmark/hps/mnistmlp/mnist_mlp.py
./benchmark/hps/mnistmlp/load_data.py
./benchmark/hps/mnistmlp-script/mnist_mlp.py
./benchmark/hps/mnistmlp-script/load_data.py
./core/cli/templates/hps/model_run.py.tmpl
```

**Comment by Deathn0t** [comment]
The reason is mostly historical. DeepHyper was initially installed and demonstrated with Keras examples. We could now just use `tf.keras`. If you can take a pass at the changes to make I will review and merge them (use the `develop` branch).

**Comment by felker** [comment]
Python 2.x support has been entirely dropped, right? I can remove stuff like
```
from __future__ import print_function
```
