### ISSUE TITLE
NAS example running

### ISSUE THREAD

**Issue by donsmj** [deephyper/deephyper#9]
Hi

I am wondering why your base example does not work!!!!!!

python -m deephyper.search.nas.ppo_a3c_sync --problem deephyper.benchmark.nas.mnist1D.problem.Problem --run deephyper.search.nas.model.run.alpha.run

By its running, the following error will occur : 

    from mpi4py import MPI
ImportError: DLL load failed: The specified module could not be found.

and the mpi4py has been installed successfully. 

Can anyone have any suggestions?

**Comment by Deathn0t** [comment]
Hi @donsmj , on what system are you trying to install deephyper ? This looks like a MPI installation issue. Did you run MPI unit tests to check if the MPI installation is well installed ?

**Comment by donsmj** [comment]
I'm working with Windows. Does it make different? I checked the MPI and has been correctly installed.

**Comment by Deathn0t** [comment]
Did you install ´mpi4py´ This way: 
https://duongtrungnghia.wordpress.com/2017/03/28/install-mpi4py-on-windows-10/

If not can you try it.

**Comment by donsmj** [comment]
Thanks! It worked well.
